
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Oct  6 2025 01:40:18 IST (Oct  5 2025 20:10:18 UTC)

// Verification Directory fv/kogge_stone_adder_16bit 

module kogge_stone_adder_16bit(A, B, CIN, CLK, RST_N, SUM, COUT);
  input [15:0] A, B;
  input CIN, CLK, RST_N;
  output [15:0] SUM;
  output COUT;
  wire [15:0] A, B;
  wire CIN, CLK, RST_N;
  wire [15:0] SUM;
  wire COUT;
  wire [15:0] B_reg;
  wire [15:0] A_reg;
  wire CIN_reg, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  DFCNQD1 COUT_reg(.CDN (RST_N), .CP (CLK), .D (n_46), .Q (COUT));
  DFCNQD1 \SUM_reg[15] (.CDN (RST_N), .CP (CLK), .D (n_45), .Q
       (SUM[15]));
  AO22D0 g3260__2398(.A1 (n_44), .A2 (n_43), .B1 (B_reg[15]), .B2
       (A_reg[15]), .Z (n_46));
  XOR2D1 g3261__5107(.A1 (n_44), .A2 (n_43), .Z (n_45));
  DFCNQD1 \SUM_reg[14] (.CDN (RST_N), .CP (CLK), .D (n_42), .Q
       (SUM[14]));
  XOR2D1 g3264__6260(.A1 (n_41), .A2 (n_40), .Z (n_42));
  AO22D0 g3263__4319(.A1 (n_41), .A2 (n_40), .B1 (B_reg[14]), .B2
       (A_reg[14]), .Z (n_44));
  DFCNQD1 \SUM_reg[13] (.CDN (RST_N), .CP (CLK), .D (n_39), .Q
       (SUM[13]));
  XOR2D1 g3267__8428(.A1 (n_38), .A2 (n_37), .Z (n_39));
  AO22D0 g3266__5526(.A1 (n_38), .A2 (n_37), .B1 (B_reg[13]), .B2
       (A_reg[13]), .Z (n_41));
  DFCNQD1 \SUM_reg[12] (.CDN (RST_N), .CP (CLK), .D (n_36), .Q
       (SUM[12]));
  AO22D0 g3269__6783(.A1 (n_35), .A2 (n_34), .B1 (B_reg[12]), .B2
       (A_reg[12]), .Z (n_38));
  XOR2D1 g3270__3680(.A1 (n_35), .A2 (n_34), .Z (n_36));
  DFCNQD1 \SUM_reg[11] (.CDN (RST_N), .CP (CLK), .D (n_33), .Q
       (SUM[11]));
  AO22D0 g3272__1617(.A1 (n_32), .A2 (n_31), .B1 (B_reg[11]), .B2
       (A_reg[11]), .Z (n_35));
  XOR2D1 g3273__2802(.A1 (n_32), .A2 (n_31), .Z (n_33));
  DFCNQD1 \SUM_reg[10] (.CDN (RST_N), .CP (CLK), .D (n_30), .Q
       (SUM[10]));
  AO22D0 g3275__1705(.A1 (n_29), .A2 (n_28), .B1 (B_reg[10]), .B2
       (A_reg[10]), .Z (n_32));
  XOR2D1 g3276__5122(.A1 (n_29), .A2 (n_28), .Z (n_30));
  DFCNQD1 \SUM_reg[9] (.CDN (RST_N), .CP (CLK), .D (n_27), .Q (SUM[9]));
  AO22D0 g3278__8246(.A1 (n_26), .A2 (n_25), .B1 (B_reg[9]), .B2
       (A_reg[9]), .Z (n_29));
  XOR2D1 g3279__7098(.A1 (n_26), .A2 (n_25), .Z (n_27));
  DFCNQD1 \SUM_reg[8] (.CDN (RST_N), .CP (CLK), .D (n_24), .Q (SUM[8]));
  AO22D0 g3281__6131(.A1 (n_23), .A2 (n_22), .B1 (B_reg[8]), .B2
       (A_reg[8]), .Z (n_26));
  XOR2D1 g3282__1881(.A1 (n_23), .A2 (n_22), .Z (n_24));
  DFCNQD1 \SUM_reg[7] (.CDN (RST_N), .CP (CLK), .D (n_21), .Q (SUM[7]));
  AO22D0 g3284__5115(.A1 (n_20), .A2 (n_19), .B1 (B_reg[7]), .B2
       (A_reg[7]), .Z (n_23));
  XOR2D1 g3285__7482(.A1 (n_20), .A2 (n_19), .Z (n_21));
  DFCNQD1 \SUM_reg[6] (.CDN (RST_N), .CP (CLK), .D (n_18), .Q (SUM[6]));
  AO22D0 g3287__4733(.A1 (n_17), .A2 (n_16), .B1 (B_reg[6]), .B2
       (A_reg[6]), .Z (n_20));
  XOR2D1 g3288__6161(.A1 (n_17), .A2 (n_16), .Z (n_18));
  DFCNQD1 \SUM_reg[5] (.CDN (RST_N), .CP (CLK), .D (n_15), .Q (SUM[5]));
  AO22D0 g3290__9315(.A1 (n_14), .A2 (n_13), .B1 (B_reg[5]), .B2
       (A_reg[5]), .Z (n_17));
  XOR2D1 g3291__9945(.A1 (n_14), .A2 (n_13), .Z (n_15));
  DFCNQD1 \SUM_reg[4] (.CDN (RST_N), .CP (CLK), .D (n_12), .Q (SUM[4]));
  AO22D0 g3293__2883(.A1 (n_11), .A2 (n_10), .B1 (B_reg[4]), .B2
       (A_reg[4]), .Z (n_14));
  XOR2D1 g3294__2346(.A1 (n_11), .A2 (n_10), .Z (n_12));
  DFCNQD1 \SUM_reg[3] (.CDN (RST_N), .CP (CLK), .D (n_9), .Q (SUM[3]));
  AO22D0 g3296__1666(.A1 (n_8), .A2 (n_7), .B1 (B_reg[3]), .B2
       (A_reg[3]), .Z (n_11));
  XOR2D1 g3297__7410(.A1 (n_8), .A2 (n_7), .Z (n_9));
  DFCNQD1 \SUM_reg[2] (.CDN (RST_N), .CP (CLK), .D (n_6), .Q (SUM[2]));
  AO22D0 g3299__6417(.A1 (n_5), .A2 (n_4), .B1 (B_reg[2]), .B2
       (A_reg[2]), .Z (n_8));
  XOR2D1 g3300__5477(.A1 (n_5), .A2 (n_4), .Z (n_6));
  DFCNQD1 \SUM_reg[1] (.CDN (RST_N), .CP (CLK), .D (n_3), .Q (SUM[1]));
  AO22D0 g3302__2398(.A1 (n_2), .A2 (n_1), .B1 (B_reg[1]), .B2
       (A_reg[1]), .Z (n_5));
  XOR2D1 g3303__5107(.A1 (n_2), .A2 (n_1), .Z (n_3));
  DFCNQD1 \SUM_reg[0] (.CDN (RST_N), .CP (CLK), .D (n_0), .Q (SUM[0]));
  FA1D0 g3305__6260(.A (CIN_reg), .B (A_reg[0]), .CI (B_reg[0]), .CO
       (n_2), .S (n_0));
  CKXOR2D1 g3313__4319(.A1 (B_reg[14]), .A2 (A_reg[14]), .Z (n_40));
  CKXOR2D1 g3316__8428(.A1 (B_reg[11]), .A2 (A_reg[11]), .Z (n_31));
  CKXOR2D1 g3317__5526(.A1 (B_reg[2]), .A2 (A_reg[2]), .Z (n_4));
  CKXOR2D1 g3318__6783(.A1 (B_reg[12]), .A2 (A_reg[12]), .Z (n_34));
  CKXOR2D1 g3319__3680(.A1 (B_reg[10]), .A2 (A_reg[10]), .Z (n_28));
  CKXOR2D1 g3320__1617(.A1 (B_reg[9]), .A2 (A_reg[9]), .Z (n_25));
  CKXOR2D1 g3315__2802(.A1 (B_reg[15]), .A2 (A_reg[15]), .Z (n_43));
  CKXOR2D1 g3310__1705(.A1 (B_reg[4]), .A2 (A_reg[4]), .Z (n_10));
  CKXOR2D1 g3307__5122(.A1 (B_reg[7]), .A2 (A_reg[7]), .Z (n_19));
  CKXOR2D1 g3308__8246(.A1 (B_reg[6]), .A2 (A_reg[6]), .Z (n_16));
  CKXOR2D1 g3309__7098(.A1 (B_reg[5]), .A2 (A_reg[5]), .Z (n_13));
  CKXOR2D1 g3306__6131(.A1 (B_reg[13]), .A2 (A_reg[13]), .Z (n_37));
  CKXOR2D1 g3311__1881(.A1 (B_reg[3]), .A2 (A_reg[3]), .Z (n_7));
  CKXOR2D1 g3312__5115(.A1 (B_reg[8]), .A2 (A_reg[8]), .Z (n_22));
  CKXOR2D1 g3314__7482(.A1 (B_reg[1]), .A2 (A_reg[1]), .Z (n_1));
  DFCNQD1 \A_reg_reg[0] (.CDN (RST_N), .CP (CLK), .D (A[0]), .Q
       (A_reg[0]));
  DFCNQD1 \A_reg_reg[9] (.CDN (RST_N), .CP (CLK), .D (A[9]), .Q
       (A_reg[9]));
  DFCNQD1 \B_reg_reg[13] (.CDN (RST_N), .CP (CLK), .D (B[13]), .Q
       (B_reg[13]));
  DFCNQD1 \B_reg_reg[8] (.CDN (RST_N), .CP (CLK), .D (B[8]), .Q
       (B_reg[8]));
  DFCNQD1 \A_reg_reg[2] (.CDN (RST_N), .CP (CLK), .D (A[2]), .Q
       (A_reg[2]));
  DFCNQD1 \A_reg_reg[8] (.CDN (RST_N), .CP (CLK), .D (A[8]), .Q
       (A_reg[8]));
  DFCNQD1 \B_reg_reg[10] (.CDN (RST_N), .CP (CLK), .D (B[10]), .Q
       (B_reg[10]));
  DFCNQD1 \A_reg_reg[4] (.CDN (RST_N), .CP (CLK), .D (A[4]), .Q
       (A_reg[4]));
  DFCNQD1 \B_reg_reg[9] (.CDN (RST_N), .CP (CLK), .D (B[9]), .Q
       (B_reg[9]));
  DFCNQD1 \A_reg_reg[10] (.CDN (RST_N), .CP (CLK), .D (A[10]), .Q
       (A_reg[10]));
  DFCNQD1 \A_reg_reg[15] (.CDN (RST_N), .CP (CLK), .D (A[15]), .Q
       (A_reg[15]));
  DFCNQD1 \A_reg_reg[1] (.CDN (RST_N), .CP (CLK), .D (A[1]), .Q
       (A_reg[1]));
  DFCNQD1 \A_reg_reg[11] (.CDN (RST_N), .CP (CLK), .D (A[11]), .Q
       (A_reg[11]));
  DFCNQD1 \B_reg_reg[5] (.CDN (RST_N), .CP (CLK), .D (B[5]), .Q
       (B_reg[5]));
  DFCNQD1 \B_reg_reg[6] (.CDN (RST_N), .CP (CLK), .D (B[6]), .Q
       (B_reg[6]));
  DFCNQD1 \B_reg_reg[1] (.CDN (RST_N), .CP (CLK), .D (B[1]), .Q
       (B_reg[1]));
  DFCNQD1 CIN_reg_reg(.CDN (RST_N), .CP (CLK), .D (CIN), .Q (CIN_reg));
  DFCNQD1 \B_reg_reg[0] (.CDN (RST_N), .CP (CLK), .D (B[0]), .Q
       (B_reg[0]));
  DFCNQD1 \B_reg_reg[15] (.CDN (RST_N), .CP (CLK), .D (B[15]), .Q
       (B_reg[15]));
  DFCNQD1 \A_reg_reg[7] (.CDN (RST_N), .CP (CLK), .D (A[7]), .Q
       (A_reg[7]));
  DFCNQD1 \A_reg_reg[13] (.CDN (RST_N), .CP (CLK), .D (A[13]), .Q
       (A_reg[13]));
  DFCNQD1 \B_reg_reg[14] (.CDN (RST_N), .CP (CLK), .D (B[14]), .Q
       (B_reg[14]));
  DFCNQD1 \A_reg_reg[14] (.CDN (RST_N), .CP (CLK), .D (A[14]), .Q
       (A_reg[14]));
  DFCNQD1 \B_reg_reg[4] (.CDN (RST_N), .CP (CLK), .D (B[4]), .Q
       (B_reg[4]));
  DFCNQD1 \B_reg_reg[11] (.CDN (RST_N), .CP (CLK), .D (B[11]), .Q
       (B_reg[11]));
  DFCNQD1 \A_reg_reg[5] (.CDN (RST_N), .CP (CLK), .D (A[5]), .Q
       (A_reg[5]));
  DFCNQD1 \B_reg_reg[3] (.CDN (RST_N), .CP (CLK), .D (B[3]), .Q
       (B_reg[3]));
  DFCNQD1 \B_reg_reg[12] (.CDN (RST_N), .CP (CLK), .D (B[12]), .Q
       (B_reg[12]));
  DFCNQD1 \A_reg_reg[3] (.CDN (RST_N), .CP (CLK), .D (A[3]), .Q
       (A_reg[3]));
  DFCNQD1 \B_reg_reg[7] (.CDN (RST_N), .CP (CLK), .D (B[7]), .Q
       (B_reg[7]));
  DFCNQD1 \A_reg_reg[6] (.CDN (RST_N), .CP (CLK), .D (A[6]), .Q
       (A_reg[6]));
  DFCNQD1 \B_reg_reg[2] (.CDN (RST_N), .CP (CLK), .D (B[2]), .Q
       (B_reg[2]));
  DFCNQD1 \A_reg_reg[12] (.CDN (RST_N), .CP (CLK), .D (A[12]), .Q
       (A_reg[12]));
endmodule
